name: Owner Mismatch Detection

on:
  workflow_dispatch:

# permissions:
#   contents: read

jobs:
  owner-mismatch:
    if: always()
    runs-on: ubuntu-latest
    steps:
         
      - uses: h0x0er/harden-runner@tls-inspect
        with:
          egress-policy: audit

      - run: curl -XPOST https://api.github.com/repos/malicious-owner/malicious-repo
      # - run: |
